package com.umai.backend.restaurant;

import java.util.LinkedHashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.DecimalMax;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import org.hibernate.annotations.BatchSize;

import com.umai.backend.area.Area;
import com.umai.backend.category.Category;
import com.umai.backend.common.domain.Auditable;
import com.umai.backend.tag.Tag;
import com.umai.backend.user.User;

/**
 * A restaurant listing.
 *
 * <p>Most descriptive fields are nullable on purpose. External sources are
 * incomplete, and the application must show what it knows rather than invent the
 * rest — see the missing-data handling in the UI.
 *
 * <p><strong>Geometry.</strong> The table also has a {@code location geometry(Point,
 * 4326)} column, generated by PostgreSQL from {@code longitude}/{@code latitude} and
 * indexed with GiST. It is intentionally not mapped here: nothing in the application
 * writes it, and leaving it unmapped keeps Hibernate schema validation independent of
 * spatial type mapping. Geospatial queries address the column directly.
 *
 * <p><strong>Rating.</strong> There is no stored rating. Aggregates are always derived
 * from {@code reviews} so the displayed score cannot drift from the underlying data.
 */
@Entity
@Table(name = "restaurants")
public class Restaurant extends Auditable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	@NotBlank
	@Size(max = 200)
	@Column(name = "name", nullable = false, length = 200)
	private String name;

	@Column(name = "description", columnDefinition = "text")
	private String description;

	@Size(max = 500)
	@Column(name = "address", length = 500)
	private String address;

	@NotNull
	@DecimalMin("-90.0")
	@DecimalMax("90.0")
	@Column(name = "latitude", nullable = false)
	private Double latitude;

	@NotNull
	@DecimalMin("-180.0")
	@DecimalMax("180.0")
	@Column(name = "longitude", nullable = false)
	private Double longitude;

	@NotNull
	@Enumerated(EnumType.STRING)
	@Column(name = "vegetarian_type", nullable = false, length = 32)
	private VegetarianType vegetarianType = VegetarianType.UNKNOWN;

	/** Null when the price band is unknown. */
	@Enumerated(EnumType.STRING)
	@Column(name = "price_range", length = 16)
	private PriceRange priceRange;

	@NotNull
	@Enumerated(EnumType.STRING)
	@Column(name = "status", nullable = false, length = 16)
	private RestaurantStatus status = RestaurantStatus.PUBLISHED;

	@NotNull
	@Enumerated(EnumType.STRING)
	@Column(name = "source", nullable = false, length = 32)
	private RestaurantSource source = RestaurantSource.USER_SUBMISSION;

	/** Identifier within {@link #source}, e.g. an OpenStreetMap node id. */
	@Size(max = 128)
	@Column(name = "source_external_id", length = 128)
	private String sourceExternalId;

	@Size(max = 500)
	@Column(name = "website_url", length = 500)
	private String websiteUrl;

	@Size(max = 32)
	@Column(name = "phone", length = 32)
	private String phone;

	/** Free text, because opening hours are wildly inconsistent across sources. */
	@Column(name = "opening_hours", columnDefinition = "text")
	private String openingHours;

	@Size(max = 1000)
	@Column(name = "image_url", length = 1000)
	private String imageUrl;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "area_id")
	private Area area;

	/** The account that submitted this listing, if it came from a user. */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "submitted_by_user_id")
	private User submittedBy;

	// @BatchSize collapses the per-row collection loads on a list page into a handful
	// of queries. Join-fetching instead would force Hibernate to paginate in memory.
	@BatchSize(size = 50)
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(
		name = "restaurant_categories",
		joinColumns = @JoinColumn(name = "restaurant_id"),
		inverseJoinColumns = @JoinColumn(name = "category_id"))
	private Set<Category> categories = new LinkedHashSet<>();

	@BatchSize(size = 50)
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(
		name = "restaurant_tags",
		joinColumns = @JoinColumn(name = "restaurant_id"),
		inverseJoinColumns = @JoinColumn(name = "tag_id"))
	private Set<Tag> tags = new LinkedHashSet<>();

	protected Restaurant() {
		// Required by JPA.
	}

	public Restaurant(String name, Double latitude, Double longitude, VegetarianType vegetarianType,
			RestaurantSource source) {
		this.name = name;
		this.latitude = latitude;
		this.longitude = longitude;
		this.vegetarianType = vegetarianType;
		this.source = source;
	}

	public void addCategory(Category category) {
		categories.add(category);
	}

	public void removeCategory(Category category) {
		categories.remove(category);
	}

	public void addTag(Tag tag) {
		tags.add(tag);
	}

	public void removeTag(Tag tag) {
		tags.remove(tag);
	}

	public Long getId() {
		return id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Double getLatitude() {
		return latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public Double getLongitude() {
		return longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public VegetarianType getVegetarianType() {
		return vegetarianType;
	}

	public void setVegetarianType(VegetarianType vegetarianType) {
		this.vegetarianType = vegetarianType;
	}

	public PriceRange getPriceRange() {
		return priceRange;
	}

	public void setPriceRange(PriceRange priceRange) {
		this.priceRange = priceRange;
	}

	public RestaurantStatus getStatus() {
		return status;
	}

	public void setStatus(RestaurantStatus status) {
		this.status = status;
	}

	public RestaurantSource getSource() {
		return source;
	}

	public void setSource(RestaurantSource source) {
		this.source = source;
	}

	public String getSourceExternalId() {
		return sourceExternalId;
	}

	public void setSourceExternalId(String sourceExternalId) {
		this.sourceExternalId = sourceExternalId;
	}

	public String getWebsiteUrl() {
		return websiteUrl;
	}

	public void setWebsiteUrl(String websiteUrl) {
		this.websiteUrl = websiteUrl;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getOpeningHours() {
		return openingHours;
	}

	public void setOpeningHours(String openingHours) {
		this.openingHours = openingHours;
	}

	public String getImageUrl() {
		return imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	public Area getArea() {
		return area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	public User getSubmittedBy() {
		return submittedBy;
	}

	public void setSubmittedBy(User submittedBy) {
		this.submittedBy = submittedBy;
	}

	public Set<Category> getCategories() {
		return categories;
	}

	public Set<Tag> getTags() {
		return tags;
	}

}
