-- Core application schema.
--
-- Conventions:
--   * Identity primary keys (BIGINT GENERATED BY DEFAULT AS IDENTITY).
--   * timestamptz for all instants; the application writes UTC.
--   * Small closed sets (status, role, ...) are VARCHAR + CHECK constraint. They map
--     to Java enums, and adding a value is a one-line migration. Open-ended sets
--     (cuisine, tags, areas) are lookup tables instead, so they stay extensible
--     without schema changes.

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(20)  NOT NULL DEFAULT 'USER',
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_users_role CHECK (role IN ('USER', 'MODERATOR', 'ADMIN'))
);

-- Case-insensitive uniqueness: "Taro" and "taro" must not both register.
CREATE UNIQUE INDEX uq_users_username_lower ON users (lower(username));
CREATE UNIQUE INDEX uq_users_email_lower ON users (lower(email));

-- ---------------------------------------------------------------------------
-- areas — Tokyo districts used by the エリア filter
-- ---------------------------------------------------------------------------
CREATE TABLE areas (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug          VARCHAR(64)  NOT NULL,
    name_ja       VARCHAR(100) NOT NULL,
    display_order INT          NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_areas_slug UNIQUE (slug)
);

-- ---------------------------------------------------------------------------
-- categories — cuisine genres (和食, カフェ, ラーメン, ...)
--
-- Vegetarian/vegan classification is NOT modelled here: it is exactly one value
-- per restaurant, so it lives in restaurants.vegetarian_type. Categories are the
-- many-valued cuisine axis.
-- ---------------------------------------------------------------------------
CREATE TABLE categories (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug          VARCHAR(64)  NOT NULL,
    name_ja       VARCHAR(100) NOT NULL,
    description   TEXT,
    display_order INT          NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_categories_slug UNIQUE (slug)
);

-- ---------------------------------------------------------------------------
-- tags — free-form extensible labels (グルテンフリー対応, テイクアウト可, ...)
-- ---------------------------------------------------------------------------
CREATE TABLE tags (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug       VARCHAR(64)  NOT NULL,
    name_ja    VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_tags_slug UNIQUE (slug)
);

-- ---------------------------------------------------------------------------
-- restaurants
-- ---------------------------------------------------------------------------
CREATE TABLE restaurants (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 VARCHAR(200)     NOT NULL,
    description          TEXT,
    address              VARCHAR(500),
    latitude             DOUBLE PRECISION NOT NULL,
    longitude            DOUBLE PRECISION NOT NULL,

    -- Derived from latitude/longitude by the database itself, so the geometry can
    -- never drift out of sync with the coordinates the application writes.
    location             geometry(Point, 4326)
                             GENERATED ALWAYS AS
                             (ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)) STORED,

    vegetarian_type      VARCHAR(32)      NOT NULL DEFAULT 'UNKNOWN',
    price_range          VARCHAR(16),
    status               VARCHAR(16)      NOT NULL DEFAULT 'PUBLISHED',

    -- Provenance, so imported data can be re-synced and attributed correctly.
    source               VARCHAR(32)      NOT NULL DEFAULT 'USER_SUBMISSION',
    source_external_id   VARCHAR(128),

    website_url          VARCHAR(500),
    phone                VARCHAR(32),
    opening_hours        TEXT,
    image_url            VARCHAR(1000),

    area_id              BIGINT REFERENCES areas (id) ON DELETE SET NULL,
    submitted_by_user_id BIGINT REFERENCES users (id) ON DELETE SET NULL,

    created_at           TIMESTAMPTZ      NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ      NOT NULL DEFAULT now(),

    CONSTRAINT ck_restaurants_latitude CHECK (latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_restaurants_longitude CHECK (longitude BETWEEN -180 AND 180),
    CONSTRAINT ck_restaurants_vegetarian_type CHECK (vegetarian_type IN (
        'VEGAN_ONLY', 'VEGETARIAN_ONLY', 'VEGAN_FRIENDLY', 'VEGETARIAN_FRIENDLY', 'UNKNOWN')),
    CONSTRAINT ck_restaurants_price_range CHECK (price_range IS NULL OR price_range IN (
        'BUDGET', 'MODERATE', 'EXPENSIVE')),
    CONSTRAINT ck_restaurants_status CHECK (status IN (
        'DRAFT', 'PENDING', 'PUBLISHED', 'REJECTED')),
    CONSTRAINT ck_restaurants_source CHECK (source IN (
        'SEED', 'USER_SUBMISSION', 'OPENSTREETMAP'))
);

-- An external record maps to at most one restaurant per source, so re-importing
-- OpenStreetMap data updates rather than duplicates.
CREATE UNIQUE INDEX uq_restaurants_source_external
    ON restaurants (source, source_external_id)
    WHERE source_external_id IS NOT NULL;

-- Geospatial index for map bounding-box and radius queries.
CREATE INDEX ix_restaurants_location ON restaurants USING GIST (location);

-- Trigram indexes for partial-word search. Japanese has no word boundaries, so
-- trigram matching suits it better than tsvector without a segmentation extension.
CREATE INDEX ix_restaurants_name_trgm ON restaurants USING GIN (name gin_trgm_ops);
CREATE INDEX ix_restaurants_description_trgm ON restaurants USING GIN (description gin_trgm_ops);

CREATE INDEX ix_restaurants_status ON restaurants (status);
CREATE INDEX ix_restaurants_vegetarian_type ON restaurants (vegetarian_type);
CREATE INDEX ix_restaurants_area_id ON restaurants (area_id);
CREATE INDEX ix_restaurants_price_range ON restaurants (price_range);

-- ---------------------------------------------------------------------------
-- join tables
-- ---------------------------------------------------------------------------
CREATE TABLE restaurant_categories (
    restaurant_id BIGINT NOT NULL REFERENCES restaurants (id) ON DELETE CASCADE,
    category_id   BIGINT NOT NULL REFERENCES categories (id) ON DELETE CASCADE,
    PRIMARY KEY (restaurant_id, category_id)
);

CREATE INDEX ix_restaurant_categories_category_id ON restaurant_categories (category_id);

CREATE TABLE restaurant_tags (
    restaurant_id BIGINT NOT NULL REFERENCES restaurants (id) ON DELETE CASCADE,
    tag_id        BIGINT NOT NULL REFERENCES tags (id) ON DELETE CASCADE,
    PRIMARY KEY (restaurant_id, tag_id)
);

CREATE INDEX ix_restaurant_tags_tag_id ON restaurant_tags (tag_id);

-- ---------------------------------------------------------------------------
-- reviews
-- ---------------------------------------------------------------------------
CREATE TABLE reviews (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    restaurant_id BIGINT      NOT NULL REFERENCES restaurants (id) ON DELETE CASCADE,
    rating        SMALLINT    NOT NULL,
    comment       TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_reviews_rating CHECK (rating BETWEEN 1 AND 5),
    -- One review per user per restaurant; updating replaces it rather than stacking.
    CONSTRAINT uq_reviews_user_restaurant UNIQUE (user_id, restaurant_id)
);

CREATE INDEX ix_reviews_restaurant_id ON reviews (restaurant_id);
CREATE INDEX ix_reviews_user_id ON reviews (user_id);
